# Generated by Django 4.0.6 on 2022-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('size', models.IntegerField()),
                ('rsvp', models.CharField(max_length=20)),
                ('consent', models.CharField(max_length=20)),
            ],
        ),
    ]
